### ISSUE TITLE
--- no python application found, check your startup logs for errors --- [pid: 491|app: -1|req: -1/3] 198.23.252.58 () {42 vars in 773 bytes} [Tue Feb 26 11:06:56 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)

### ISSUE THREAD

**Issue by lost1984** [131mm/ssweb-web.py#1]
debian 8
Method 2方式按照的，报错

--SyntaxError: invalid syntax
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 491, cores: 1)
- no python application found, check your startup logs for errors ---
[pid: 491|app: -1|req: -1/3] xxx.xxx.xxx.xxx() {42 vars in 773 bytes} [Tue Feb 26 11:06:56 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)

**Comment by 131mm** [comment]
报错的log太少，再bash run.sh一次把所有log发上来看一下

**Comment by lost1984** [comment]
root@198-23-252-58-host:~# cd /usr/local/ssweb-web.py
root@198-23-252-58-host:/usr/local/ssweb-web.py# python3 -m venv venv
root@198-23-252-58-host:/usr/local/ssweb-web.py# bash run.sh
Requirement already satisfied (use --upgrade to upgrade): Jinja2==2.10 in ./venv                                                                                                                     /lib/python3.4/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe==1.1.0 in .                                                                                                                     /venv/lib/python3.4/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): uWSGI==2.0.17.1 in ./v                                                                                                                     env/lib/python3.4/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): web.py==0.40.dev1 in .                                                                                                                     /venv/lib/python3.4/site-packages (from -r requirements.txt (line 4))
Cleaning up...
root@198-23-252-58-host:/usr/local/ssweb-web.py# *** Starting uWSGI 2.0.17.1 (64                                                                                                                     bit) on [Wed Feb 27 08:58:52 2019] ***
compiled with version: 4.9.2 on 26 February 2019 02:56:44
os: Linux-4.11.8-041108-generic #201706290836 SMP Thu Jun 29 12:38:45 UTC 2017
nodename: 198-23-252-58-host
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /usr/local/ssweb-web.py
detected binary path: /usr/local/ssweb-web.py/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 1857
your memory page size is 4096 bytes
detected max file descriptor number: 65536
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8008 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
Python version: 3.4.2 (default, Feb  7 2019, 06:11:23)  [GCC 4.9.2]
*** Python threads support is disabled. You can enable it with --enable-threads                                                                                                                      ***
Python main interpreter initialized at 0x1a006e0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72904 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "./ssweb.py", line 2, in <module>
    import ssr
  File "./ssr.py", line 231
    '''返回下一个可使用的username'''
       ^
SyntaxError: invalid syntax
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 500, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 500|app: -1|req: -1/1] 183.6.104.24 () {40 vars in 740 bytes} [Wed Feb 27                                                                                                                      08:59:08 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers i                                                                                                                     n 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 500|app: -1|req: -1/2] 183.6.104.24 () {40 vars in 716 bytes} [Wed Feb 27                                                                                                                      08:59:09 2019] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500)                                                                                                                      2 headers in 83 bytes (0 switches on core 0)

**Comment by 131mm** [comment]
我检查了那个函数，那里应该是没有语法错误的。另外我今天优化了数据确认，你git pull拉一遍看看能不能解决
