### ISSUE TITLE
希望加个时间限定

### ISSUE THREAD

**Issue by OvO-nei** [131mm/ssweb-web.py#3]
跟人合租一块用，然后中途加进来，不方便收费，希望可以设定xx天关闭端口之类的，非常感谢
感谢大大的无私奉献。
欸，对了 有捐赠通道吗

**Comment by 131mm** [comment]
其实只要不是那种天天十多个小时看youtube的，用不了多少流量。这个关闭端口的功能可以用设定流量来代替
