### ISSUE TITLE
安装老爱出错

### ISSUE THREAD

**Issue by ghost** [131mm/ssweb-web.py#4]
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x2264f10 pid: 21858 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 21858, cores: 1)

**Comment by 131mm** [comment]
你贴的这些log都没提供任何有用的信息，甚至连一个error都没报

**Comment by ghost** [comment]
运行最后的run.sh就一直停在这一步不动了
贴图：
https://ws3.sinaimg.cn/large/005LHbWaly1g1rrai9aaoj30wq0qun1u.jpg

**Comment by ghost** [comment]
补：
https://ws3.sinaimg.cn/large/005LHbWaly1g1rrmu69pxj30vu0qgwkh.jpg

**Comment by 131mm** [comment]
1、你是按照method1 一步一步来的还是method2 ？
2、你有没有去访问你的网址？
3、如果访问了，报错是什么？welcome to nginx? 还是50x服务器内部错误？
4、图中log并没有有用信息

**Comment by Azureleej** [comment]
method1 / 2 都试了
访问网址就是404 Not Found
应该和uWSGI有关

**Comment by ghost** [comment]
method1 / 2 都试了
访问网址就是404 Not Found
挺喜欢这个项目的 是在下无能了

**Comment by 131mm** [comment]
404是nginx没有配置对，那个是蛮简单的，你重新配置一下nginx，其他都不变，具体操作就是改域名，把配置文件复制过去，重载nginx
